import { useEffect, useState } from "react";
import API from "../services/api";
import Loader from "../components/Loader";

interface Requirement {

    requirement_id:number;

    canteen_name:string;

    product_id:number;

    required_qty:number;

    requirement_date:string;

    generated_by:string;

    status:string;

}

function NextDayRequirement(){

    const [requirements,setRequirements]=useState<Requirement[]>([]);

    const [loading,setLoading]=useState(true);

    useEffect(()=>{

        loadRequirements();

    },[]);

    const loadRequirements=async()=>{

        try{

            const res=await API.get("/next-day-requirement");

            setRequirements(res.data);

        }

        catch(err){

            console.log(err);

        }

        finally{

            setLoading(false);

        }

    };

    if(loading) return <Loader/>;

    return(

        <div>

            <div className="page-header">

                <h1>Next Day Requirement</h1>

                <button
                    className="btn"
                    onClick={loadRequirements}
                >
                    Refresh
                </button>

            </div>

            <table className="inventory-table">

                <thead>

                    <tr>

                        <th>Canteen</th>

                        <th>Product ID</th>

                        <th>Required Qty</th>

                        <th>Date</th>

                        <th>Generated By</th>

                        <th>Status</th>

                    </tr>

                </thead>

                <tbody>

                    {requirements.map(req=>(

                        <tr key={req.requirement_id}>

                            <td>{req.canteen_name}</td>

                            <td>{req.product_id}</td>

                            <td>{req.required_qty}</td>

                            <td>{req.requirement_date}</td>

                            <td>{req.generated_by}</td>

                            <td>

                                <span
                                    className={
                                        req.status==="Generated"
                                        ? "status-ok"
                                        : "status-low"
                                    }
                                >
                                    {req.status}
                                </span>

                            </td>

                        </tr>

                    ))}

                </tbody>

            </table>

        </div>

    );

}

export default NextDayRequirement;  